tables={
    'table1':{
        'name':'Table-1',
        'items':[],
        'totalAmount':0,
        'itemsCount':0,
    },
    'table2':{
        'name':'Table-2',
        'items':[],
        'totalAmount':0,
        'itemsCount':0,
    },
    'table3':{
        'name':'Table-3',
        'items':[],
        'totalAmount':0,
        'itemsCount':0,
    },
    'table4':{
        'name':'Table-4',
        'items':[],
        'totalAmount':0,
        'itemsCount':0,
    },
}
menu_items={
    'fitem1':{
        'name':'Pizza',
        'price':105.00,
        'count':1
    },
    'fitem2':{
        'name':'French Fries',
        'price':200.00,
        'count':1
    },
    'fitem3':{
        'name':'Burger',
        'price':350.00,
        'count':1
    },
    'fitem4':{
        'name':'Noodles',
        'price':105.00,
        'count':1
    },
    'fitem5':{
        'name':'Fried Rice',
        'price':240.00,
        'count':1
    },
    'fitem6':{
        'name':'Manchuria',
        'price':240.00,
        'count':1
    },
    'fitem7':{
        'name':'Chhole Bhature',
        'price':105.00,
        'count':1
    },
    'fitem8':{
        'name':'Masala Chai',
        'price':24.00,
        'count':1
    },
    'fitem9':{
        'name':'Jalebi',
        'price':200.00,
        'count':1
    },
    'fitem10':{
        'name':'Hyderabadi Biryani',
        'price':540.00,
        'count':1
    },
    'fitem11':{
        'name':'Masala Dosa',
        'price':85.00,
        'count':1
    },
    'fitem12':{
        'name':'Falooda',
        'price':95.00,
        'count':1
    },
    
}